version: 2
project_name: heimdall

builds:
  - id: heimdall
    main: ./cmd/heimdall
    binary: heimdall
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'

release:
  github:
    owner: 0merUfuk
    name: heimdall
